//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonationOffers
    {
        public int Id { get; set; }
        public int UserCode { get; set; }
        public int DonationCode { get; set; }
    
        public virtual Donations Donations { get; set; }
        public virtual USERS USERS { get; set; }
    }
}
