//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GMH
    {
        public int GmhCode { get; set; }
        public string GmeName { get; set; }
        public string Adress { get; set; }
        public int UserCode { get; set; }
        public int CategoryCode { get; set; }
        public byte[] Picture { get; set; }
        public Nullable<int> Amount { get; set; }
        public string FreeDescription { get; set; }
        public bool IsDisposable { get; set; }
        public Nullable<int> SecurityDepositAmount { get; set; }
        public string Status { get; set; }
    
        public virtual CategoryGMH CategoryGMH { get; set; }
        public virtual USER USER { get; set; }
    }
}
