//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LENDINGS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LENDINGS()
        {
            this.OPINIONS = new HashSet<OPINIONS>();
        }
    
        public int LendingCode { get; set; }
        public int UserCode { get; set; }
        public int ProductCode { get; set; }
        public Nullable<System.DateTime> LendingDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public string Comment { get; set; }
    
        public virtual PRODUCTtoGMH PRODUCTtoGMH { get; set; }
        public virtual USERS USERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPINIONS> OPINIONS { get; set; }
    }
}
