//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Charity_DBEntities : DbContext
    {
        public Charity_DBEntities()
            : base("name=Charity_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CategoryGMH> CategoryGMHs { get; set; }
        public virtual DbSet<GMH> GMHs { get; set; }
        public virtual DbSet<LENDING> LENDINGS { get; set; }
        public virtual DbSet<OPINION> OPINIONS { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<PRODUCTtoGMH> PRODUCTtoGMHs { get; set; }
        public virtual DbSet<USER> USERS { get; set; }
        public virtual DbSet<Image> Images { get; set; }
        public virtual DbSet<Donation> Donations { get; set; }
    }
}
