//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestForLoan
    {
        public int RequestCode { get; set; }
        public int UserCode { get; set; }
        public int ProductCode { get; set; }
        public System.DateTime RequestDate { get; set; }
        public Nullable<int> Amount { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual USER USER { get; set; }
    }
}
